<?php

namespace AppBundle\Component\Repository;


use AppBundle\Component\Entity\Product;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
interface ProductRepository
{

    public function createProduct(Product $product);
    public function listProduct();
}
